--1
SELECT * FROM PAYMENT WHERE TYPE_ID = (SELECT id FROM PAYMENTTYPE WHERE NAME = 'MONTHLY');
--2
select * from MARK where SUBJECT_ID in (select SUBJECT.ID from SUBJECT where NAME = 'Art');
--3
select * from STUDENT where ID in (select distinct STUDENT_ID from PAYMENT where TYPE_ID = (select ID from PAYMENTTYPE where NAME = 'WEEKLY'));
--4
SELECT * FROM STUDENT WHERE ID IN (SELECT M.STUDENT_ID FROM MARK M WHERE M.SUBJECT_ID = (SELECT S.ID FROM SUBJECT S WHERE S.NAME = 'Math'));