--1
SELECT BIRTHDAY
FROM STUDENT
ORDER BY BIRTHDAY DESC
LIMIT 1;
--2
SELECT PAYMENT_DATE
FROM PAYMENT
ORDER BY PAYMENT_DATE
LIMIT 1;
--3
SELECT AVG(MARK)
FROM MARK
WHERE SUBJECT_ID = (
    SELECT ID
    FROM SUBJECT
    WHERE NAME = 'Math');
--4
SELECT MIN(AMOUNT)
FROM PAYMENT
WHERE TYPE_ID = (
    SELECT ID FROM PAYMENTTYPE WHERE NAME = 'WEEKLY');