--1
SELECT S.NAME
FROM MARK M
INNER JOIN STUDENT S on M.STUDENT_ID = S.ID
GROUP BY M.STUDENT_ID
HAVING AVG(M.MARK) > 8;
--2
SELECT ID, NAME
FROM STUDENT
WHERE ID IN (
    SELECT STUDENT_ID
    FROM MARK
    GROUP BY STUDENT_ID
    HAVING MIN(MARK) > 7);
--3
SELECT ID, NAME
FROM STUDENT
WHERE ID IN (
    SELECT STUDENT_ID
    FROM PAYMENT
    WHERE PAYMENT_DATE BETWEEN '20190101' AND '20191231'
    GROUP BY STUDENT_ID
    HAVING COUNT(ID) > 2);